# web server
server:
  port: 9082

# spring auto configure
spring:
  application:
    name: hello-logging


# logging
logging:
  level:
    root: DEBUG
    org:
      springframework: WARN
      example: DEBUG

